[feat]: Добавил сборку docker-образа

diff --git a/.github/workflows/pipelines.yml b/.github/workflows/pipelines.yml
--- a/.github/workflows/pipelines.yml
+++ b/.github/workflows/pipelines.yml
@@ -74,3 +74,26 @@ jobs:
 
       - name: 👉🏼 Запускаем тесты
         run: ./mvnw clean package
+  dockerize:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем гит сабмодули
+        run: |
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем install + docker build + docker push
+        run: ./mvnw clean install
