Настроить деплой микросервисов (#16)
* [feat]: Добавил сборку docker-образа

* [fix]: Вырубил тесты при сборке docker-образа

* [fix]: Добавил переменные

* [fix]: Добавил mainClass

* [fix]: Добавил проброс переменных из пайплайна в pom.xml

* [fix]: Добавил кавычки вокруг пароля

* [feat]: Добавил профиль dev, сделал, чтобы dockerize job запускалать только при пуше в main

* [feat]: Добавил deploy

* [fix]: Сделал deploy только после dockerize

* [fix]: Поправил название контейнера

* [fix]: Добавил передачу env переменных при запуске контейнера

* [fix]: Поправил stop на rm при перезапуске контейнера

* [fix]: Поправил url базы

* [fix]: Поправил ddl-auto

* [fix]: Поправил обнoвление контейнера на пайплайнах

* [fix]: Сделал джобы dockerize и deploy только при мердже в main

* [feat]: Поправил пайплайны

* [fix]: Добавил деплой user-service

* [fix]: Фикс

---------

Co-authored-by: DaPiankov <DaPiankov@croc.ru>

diff --git a/.github/workflows/pipelines.yml b/.github/workflows/pipelines.yml
--- a/.github/workflows/pipelines.yml
+++ b/.github/workflows/pipelines.yml
@@ -1,4 +1,4 @@
-name: 🔥 Сборка и тесты МР-а
+name: 🔥 Сборка, тесты и деплой
 
 on:
   push:
@@ -14,6 +14,7 @@ jobs:
 
       - name: 👉🏼 Инициализируем гит сабмодули
         run: |
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
           git submodule update --init --remote --recursive
           git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
 
@@ -37,6 +38,7 @@ jobs:
 
       - name: 👉🏼 Инициализируем гит сабмодули
         run: |
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
           git submodule update --init --remote --recursive
           git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
 
@@ -60,6 +62,7 @@ jobs:
 
       - name: 👉🏼 Инициализируем гит сабмодули
         run: |
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
           git submodule update --init --remote --recursive
           git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
 
@@ -74,3 +77,50 @@ jobs:
 
       - name: 👉🏼 Запускаем тесты
         run: ./mvnw clean package
+  dockerize:
+    if: ${{ github.ref == 'refs/heads/main' }}
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем гит сабмодули
+        run: |
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем install + docker build + docker push
+        run: ./mvnw -DskipTests -DregistryUsername=${{ vars.CI_REGISTRY_USER }} -DregistryPassword='${{ vars.CI_REGISTRY_PASSWORD }}' clean install
+  deploy:
+    if: ${{ github.ref == 'refs/heads/main' }}
+    runs-on: ubuntu-latest
+    needs: dockerize
+    steps:
+      - name: 👉🏼 Устанавливаем sshpass
+        run: sudo apt update && sudo apt install -y sshpass
+
+      - name: 👉🏼 Подключаемся к удаленному серверу
+        run: sshpass -p ${{ vars.REMOTE_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ vars.REMOTE_SERVER_HOST }} "
+          echo Connected to the remote server ${{ vars.REMOTE_SERVER_HOST }}!"
+
+      - name: 👉🏼 Перезапускаем контейнер с приложением
+        run: sshpass -p ${{ vars.REMOTE_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ vars.REMOTE_SERVER_HOST }} "
+          docker stop ${{ vars.CI_REGISTRY_USER }}_${{ vars.USER_SERVICE_REPOSITORY_NAME }} || true &&
+          docker rm ${{ vars.CI_REGISTRY_USER }}_${{ vars.USER_SERVICE_REPOSITORY_NAME }} || true &&
+          docker rmi $(docker images -f "dangling=true" -q) &&
+          docker rmi ${{ vars.CI_REGISTRY_USER }}/${{ vars.USER_SERVICE_REPOSITORY_NAME }}:1.0.0 -f || true &&
+          docker pull ${{ vars.CI_REGISTRY_USER }}/${{ vars.USER_SERVICE_REPOSITORY_NAME }}:1.0.0 || true &&
+          docker rmi $(docker images -f "dangling=true" -q) &&
+          docker network create -d bridge ${{ vars.DOCKER_NETWORK_NAME }} || true &&
+          docker run -d --rm -e REMOTE_SERVER_HOST=${{ vars.REMOTE_SERVER_HOST }} -e DOCKER_NETWORK_NAME=${{ vars.DOCKER_NETWORK_NAME }} -e POSTGRES_DATABASE_USERNAME=${{ vars.POSTGRES_DATABASE_USERNAME }} -e POSTGRES_DATABASE_PASSWORD=${{ vars.POSTGRES_DATABASE_PASSWORD }} -e JWT_SECRET=${{ vars.JWT_SECRET }} --name ${{ vars.CI_REGISTRY_USER }}_${{ vars.USER_SERVICE_REPOSITORY_NAME }} --network ${{ vars.DOCKER_NETWORK_NAME }} -p ${{ vars.USER_SERVICE_CONTAINER_PORT }}:${{ vars.USER_SERVICE_CONTAINER_PORT }} ${{ vars.CI_REGISTRY_USER }}/${{ vars.USER_SERVICE_REPOSITORY_NAME }}:1.0.0"
